In [1]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings("ignore")
import matplotlib.pyplot as  plt
import seaborn as sns

In [2]:
data = pd.read_csv( r"C:\Users\samar\OneDrive\Desktop\code\train_data1.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,B96 B98,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,B96 B98,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,B96 B98,Q

In [3]:
# X =data.iloc[:,[2,4,5]]
X = data[["Pclass","Sex","Age"]]
X

     Pclass     Sex   Age
0         3    male  22.0
1         1  female  38.0
2         3  female  26.0
3         1  female  35.0
4         3    male  35.0
..      ...     ...   ...
886       2    male  27.0
887       1  female  19.0
888       3  female  28.0
889       1    male  26.0
890       3    male  32.0

[891 rows x 3 columns]

In [4]:
# y = data.iloc[:,1:2]
y = data["Survived"]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X["Sex"] = le.fit_transform(X["Sex"])
X

     Pclass  Sex   Age
0         3    1  22.0
1         1    0  38.0
2         3    0  26.0
3         1    0  35.0
4         3    1  35.0
..      ...  ...   ...
886       2    1  27.0
887       1    0  19.0
888       3    0  28.0
889       1    1  26.0
890       3    1  32.0

[891 rows x 3 columns]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0 )

In [7]:
# X.iloc[:,4] = le.fit_transform(X.iloc[:,4])
# X.iloc[:, 4] = le.fit_transform(X.iloc[:, 4].values.reshape(-1, 1))

In [8]:
from lazypredict.Supervised import LazyClassifier
cls_1 = LazyClassifier()
models, predictions = cls_1.fit(X_train, X_test, y_train, y_test)
models

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 29/29 [00:00<00:00, 34.04it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
KNeighborsClassifier,0.85,0.83,0.83,0.85,0.02
XGBClassifier,0.83,0.82,0.82,0.83,0.05
ExtraTreeClassifier,0.84,0.81,0.81,0.83,0.01
ExtraTreesClassifier,0.83,0.81,0.81,0.83,0.13
RandomForestClassifier,0.83,0.81,0.81,0.82,0.16
DecisionTreeClassifier,0.82,0.80,0.80,0.82,0.02
LGBMClassifier,0.82,0.80,0.80,0.81,0.06
AdaBoostClassifier,0.80,0.80,0.80,0.81,0.11
NearestCentroid,0.79,0.80,0.80,0.80,0.02
LabelPropagation,0.81,0.79,0.79,0.81,0.03
LabelSpreading,0.81,0.79,0.79,0.81,0.02
SVC,0.81,0.79,0.79,0.81,0.02
BaggingClassifier,0.80,0.79,0.79,0.80,0.03
LogisticRegression,0.80,0.79,0.79,0.80,0.02
SGDClassifier,0.79,0.78,0.78,0.79,0.02
GaussianNB,0.79,0.77,0.77,0.79,0.00
BernoulliNB,0.79,0.77,0.77,0.79,0.01
QuadraticDiscriminantAnalysis,0.78,0.77,0.77,0.78,0.02
NuSVC,0.79,0.77,0.77,0.79,0.02
CalibratedClassifierCV,0.78,0.77,0.77,0.78,0.06
RidgeClassifierCV,0.78,0.76,0.76,0.78,0.01
LinearSVC,0.78,0.76,0.76,0.78,0.00
RidgeClassifier,0.78,0.76,0.76,0.78,0.02
LinearDiscriminantAnalysis,0.78,0.76,0.76,0.78,0.02
PassiveAggressiveClassifier,0.74,0.71,0.71,0.73,0.01
Perceptron,0.70,0.70,0.70,0.70,0.00
DummyClassifier,0.61,0.50,0.50,0.47,0.01

In [9]:
# from xgboost import XGBClassifier
# cls= XGBClassifier()
# cls.fit(X_train, y_train)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
# cl = KNeighborsClassifier(algorithm='brute', leaf_size=50, metric='minkowsk', n_neighbors=19, p=10, weights='distance')
cl = KNeighborsClassifier(n_neighbors=5, metric='minkowski', weights='distance',algorithm='brute')
# cl = KNeighborsClassifier()

In [11]:
cl.fit(X_train, y_train)

KNeighborsClassifier(algorithm='brute', weights='distance')

In [12]:
y_pred = cl.predict(X_test)
y_pred_1 = cl.predict(X_train)

In [13]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
ac

0.8100558659217877

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val = cross_val_score(cl,X,y,cv = 6).mean()

In [16]:
cross_val

0.7957252554567992

In [17]:
train_accuracy = accuracy_score(y_train,y_pred_1)
train_accuracy

0.8665730337078652

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[101,   9],
       [ 25,  44]], dtype=int64)

In [19]:
# from sklearn.metrics import accuracy_score
# ac = accuracy_score(y_test,y_pred)
# ac

In [20]:
# bias = cls.fit(X_train,y_train)
# bias

In [21]:
# variance = cls.fit(y_test, y_train)
# variance

In [22]:
import pickle
pickle.dump(cls, open("Titanic.pkl", "wb"))

In [23]:
import os 
os.getcwd()